# Generated by Django 5.0.2 on 2024-04-04 18:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_code', models.CharField(max_length=10)),
                ('number_of_solar_panels', models.IntegerField(null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('panel_orientation', models.FloatField(max_length=10, null=True)),
                ('panel_tilt', models.FloatField(max_length=10, null=True)),
                ('washing_machine_selected', models.BooleanField(default=False)),
                ('tumble_dryer_selected', models.BooleanField(default=False)),
                ('temperature', models.FloatField(max_length=50, null=True)),
                ('cloud_cover', models.CharField(max_length=50, null=True)),
                ('wind_speed', models.FloatField(max_length=50, null=True)),
                ('wind_direction', models.CharField(max_length=50, null=True)),
                ('humidity', models.FloatField(max_length=50, null=True)),
                ('precipitation', models.CharField(max_length=50, null=True)),
                ('solar_azimuth', models.FloatField(max_length=50, null=True)),
                ('solar_altitude', models.FloatField(max_length=50, null=True)),
                ('daily_solar_output', models.FloatField(max_length=50, null=True)),
                ('optimal_time', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('optimal_power', models.FloatField(max_length=50, null=True)),
                ('wm_optimal_usage', models.JSONField(blank=True, null=True)),
                ('td_optimal_usage', models.JSONField(blank=True, null=True)),
                ('hourly_solar_production', models.JSONField(blank=True, null=True)),
                ('appliance_consumption', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplianceConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appliance_name', models.CharField(max_length=50)),
                ('sequence', models.IntegerField()),
                ('consumption', models.FloatField()),
            ],
            options={
                'unique_together': {('appliance_name', 'sequence')},
            },
        ),
    ]
