# Generated by Django 5.0.2 on 2024-03-23 15:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='optimal_power',
            field=models.FloatField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='optimal_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
