# Generated by Django 5.0.2 on 2024-02-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='react',
            name='no_solar_panels',
            field=models.IntegerField(),
        ),
    ]
