# Generated by Django 5.0.2 on 2024-03-18 14:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='panel_orientation',
            field=models.FloatField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='panel_tilt',
            field=models.FloatField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='solar_irradiance',
            field=models.FloatField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
