# Generated by Django 5.0.2 on 2024-03-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='temperature',
            field=models.FloatField(null=True),
        ),
    ]
