# Generated by Django 5.0.2 on 2024-03-23 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solarApp', '0002_submission_optimal_power_submission_optimal_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='solar_irradiance',
            new_name='daily_solar_output',
        ),
    ]
