# Generated by Django 5.0.2 on 2024-03-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarApp', '0002_alter_submission_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='temperature',
            field=models.FloatField(max_length=50, null=True),
        ),
    ]
