# Generated by Django 5.0.2 on 2024-02-23 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solarApp', '0003_submission_delete_react'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='solar_panels',
            new_name='number_of_solar_panels',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='submission_date',
        ),
    ]
