# Generated by Django 5.0.2 on 2024-03-15 15:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarApp', '0003_alter_submission_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
