# Generated by Django 5.0.2 on 2024-03-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarApp', '0003_rename_solar_irradiance_submission_daily_solar_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='td_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='wm_selected',
            field=models.BooleanField(default=False),
        ),
    ]
