# Generated by Django 5.0.2 on 2024-03-19 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solarApp', '0003_submission_dhi_submission_dni_submission_ghi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='dhi',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='ghi',
        ),
    ]
