# Generated by Django 5.0.2 on 2024-03-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarApp', '0004_submission_td_selected_submission_wm_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='optimal_usage',
            field=models.JSONField(null=True),
        ),
    ]
