# Generated by Django 5.0.2 on 2024-03-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarApp', '0005_submission_optimal_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='optimal_usage',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
