# Generated by Django 5.0.2 on 2024-03-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarApp', '0005_submission_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='cloud_cover',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='solar_irradiance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='temperature',
            field=models.FloatField(null=True),
        ),
    ]
