# Generated by Django 5.0.2 on 2024-03-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarApp', '0006_submission_cloud_cover_submission_solar_irradiance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='solar_irradiance',
        ),
        migrations.AlterField(
            model_name='submission',
            name='temperature',
            field=models.FloatField(max_length=50, null=True),
        ),
    ]
