# Generated by Django 5.0.2 on 2024-03-24 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solarApp', '0006_alter_submission_optimal_usage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='td_selected',
            new_name='tumble_dryer',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='wm_selected',
            new_name='washing_machine',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='optimal_usage',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='tumble_dryer_data',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='washing_machine_data',
        ),
    ]
