# Generated by Django 5.0.2 on 2024-03-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarApp', '0007_remove_submission_solar_irradiance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='humidity',
            field=models.FloatField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='precipitation',
            field=models.FloatField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='wind_direction',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='wind_speed',
            field=models.FloatField(max_length=50, null=True),
        ),
    ]
