# Generated by Django 5.0.2 on 2024-03-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarApp', '0007_rename_td_selected_submission_tumble_dryer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('day_of_week', models.CharField(max_length=9)),
                ('total_consumption_wh', models.FloatField()),
            ],
        ),
    ]
