# Generated by Django 5.0.2 on 2024-03-24 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solarApp', '0008_appliance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='tumble_dryer',
            new_name='tumble_dryer_selected',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='washing_machine',
            new_name='washing_machine_selected',
        ),
    ]
