# Generated by Django 5.0.2 on 2024-03-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarApp', '0008_submission_humidity_submission_precipitation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='solar_altitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='solar_azimuth',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='submission',
            name='humidity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='precipitation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='temperature',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='wind_speed',
            field=models.FloatField(null=True),
        ),
    ]
