# Generated by Django 5.0.2 on 2024-03-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarApp', '0009_submission_solar_altitude_submission_solar_azimuth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='solar_radiation',
            field=models.JSONField(null=True),
        ),
    ]
