# Generated by Django 5.0.2 on 2024-03-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarApp', '0009_rename_tumble_dryer_submission_tumble_dryer_selected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='optimal_usage',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
