# Generated by Django 5.0.2 on 2024-03-24 16:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarApp', '0010_submission_optimal_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='optimal_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
