# Generated by Django 5.0.2 on 2024-03-12 19:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarApp', '0010_submission_solar_radiation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='submission',
            name='temperature',
            field=models.FloatField(max_length=50, null=True),
        ),
    ]
