# Generated by Django 5.0.2 on 2024-03-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarApp', '0011_alter_submission_date_alter_submission_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='humidity',
            field=models.FloatField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='wind_speed',
            field=models.FloatField(max_length=50, null=True),
        ),
    ]
