# Generated by Django 5.0.2 on 2024-03-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarApp', '0011_alter_submission_optimal_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='optimal_usage',
        ),
        migrations.AddField(
            model_name='submission',
            name='td_optimal_usage',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='wm_optimal_usage',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
