# Generated by Django 5.0.2 on 2024-03-12 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solarApp', '0012_alter_submission_humidity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='solar_radiation',
        ),
    ]
