# Generated by Django 5.0.2 on 2024-03-26 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solarApp', '0012_remove_submission_optimal_usage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appliance',
        ),
    ]
