# Generated by Django 5.0.2 on 2024-03-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarApp', '0013_remove_submission_solar_radiation'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='solar_radiation',
            field=models.JSONField(null=True),
        ),
    ]
