# Generated by Django 5.0.2 on 2024-03-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarApp', '0013_delete_appliance'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='appliance_consumption',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='hourly_solar_production',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
