# Generated by Django 5.0.2 on 2024-03-28 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarApp', '0014_submission_appliance_consumption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplianceConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appliance_name', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('consumption', models.FloatField()),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarApp.submission')),
            ],
        ),
    ]
