# Generated by Django 5.0.2 on 2024-03-15 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solarApp', '0014_submission_solar_radiation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='solar_radiation',
        ),
    ]
