# Generated by Django 5.0.2 on 2024-03-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarApp', '0015_applianceconsumption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applianceconsumption',
            name='submission',
        ),
        migrations.AlterField(
            model_name='applianceconsumption',
            name='timestamp',
            field=models.TimeField(),
        ),
    ]
