# Generated by Django 5.0.2 on 2024-03-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarApp', '0015_remove_submission_solar_radiation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='solar_altitude',
            field=models.FloatField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='solar_azimuth',
            field=models.FloatField(max_length=50, null=True),
        ),
    ]
