# Generated by Django 5.0.2 on 2024-03-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarApp', '0016_remove_applianceconsumption_submission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applianceconsumption',
            name='appliance_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='applianceconsumption',
            unique_together={('appliance_name', 'timestamp')},
        ),
    ]
