# Generated by Django 5.0.2 on 2024-04-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarApp', '0017_alter_applianceconsumption_appliance_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='number_of_solar_panels',
            field=models.IntegerField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='panel_orientation',
            field=models.FloatField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='panel_tilt',
            field=models.FloatField(max_length=4, null=True),
        ),
    ]
