name: Django Backend CI

on:
  pull_request:
    branches: [ main ] 
  workflow_dispatch:

jobs:
  build-and-test: 
    runs-on: ubuntu-latest 

    steps:
      - name: Code
        uses: actions/checkout@v3

      - name: Set up Python 
        uses: actions/setup-python@v4 
        with:
          python-version: '3.12'

      - name: Run Linting
        run: flake8 .

      - name: Build Docker Image 
        run: docker build -t gcr.io/modular-magpie-414414/django-backend . 

      - name: Run Container
        run: docker run -it gcr.io/modular-magpie-414414/django-backend

      - name: Check Container Status
        run: docker ps
